refine cr4 output description
ldbc/ldbc_finbench_docs pull request #87
Opened 2023-05-22 12:07 UTC by BingTong0

2023-05-22 14:36 UTC, qishipengqsp requested changes

2023-05-22 14:36 UTC, qishipengqsp commented on query-specifications/transaction-complex-read-04.yaml
> +  (*edge1*). If *edge1* does not exist, the result size is 0.
改成“return with empty results”会更好一些？

2023-05-23 01:21 UTC, BingTong0 commented on query-specifications/transaction-complex-read-04.yaml
> +  (*edge1*). If *edge1* does not exist, the result size is 0.
empty results 会有歧义吗，比如返回size是1的，但是里面每一项是null，这算empty吗

2023-05-26 06:54 UTC, qishipengqsp commented on query-specifications/transaction-complex-read-04.yaml
> +  (*edge1*). If *edge1* does not exist, the result size is 0.
只是觉得`the result size is 0.`这个说法挺怪的

2023-05-26 06:54 UTC, qishipengqsp commented on query-specifications/transaction-complex-read-04.yaml
> +  (*edge1*). If *edge1* does not exist, the result size is 0.
就现在这样先写着吧

2023-05-26 06:54 UTC, qishipengqsp approved these changes

2023-05-26 06:54 UTC, merged